CFLAGS     = -O3 -std=gnu99 -Wno-unused-result -D_GNU_SOURCE
LDLIBS     = -lm -static
TARGETARCH =

all:
	$(MAKE) -f Makefile CFLAGS="$(CFLAGS)" LDLIBS="$(LDLIBS)" TARGETARCH="$(TARGETARCH)" navdconv

.PHONY: clean
clean:
	@:
