CC         = x86_64-w64-mingw32-gcc
CFLAGS     = -O3 -std=gnu99 -DCOMPAT_STRCASESTR=1 -DCOMPAT_STRERROR_R=1 -DCOMPAT_STRNDUP=1 -DCOMPAT_STRSEP=1
NDCONV_EXE = navdconv.exe

all:
	$(MAKE) -f Makefile CC="$(CC)" CFLAGS="$(CFLAGS)" NDCONV_EXE="$(NDCONV_EXE)" all

.PHONY: clean
clean:
	$(MAKE) -f Makefile NDCONV_EXE="$(NDCONV_EXE)" clean
