CC         = x86_64-w64-mingw32-gcc
CFLAGS     = -O3 -std=gnu99 -DMINGW_HAS_SECURE_API -DCOMPAT_MINGW_DEFAULT=1
NDCONV_EXE = navdconv.exe
TARGETARCH =

LIBACU_DIR = libacfutils-redist
LIBACU_INC = -I$(LIBACU_DIR)/include
LIBACU_LIB = -L$(LIBACU_DIR)/win64/lib -lacfutils

all:
	$(MAKE) -f Makefile CC="$(CC)" CFLAGS="$(CFLAGS)" TARGETARCH="$(TARGETARCH)" NDCONV_EXE="$(NDCONV_EXE)" LIBACU_INC="$(LIBACU_INC)" LIBACU_LIB="$(LIBACU_LIB)" navdconv

.PHONY: clean
clean:
	$(RM) $(NDCONV_EXE)
